// <auto-generated>
// The SignalR NotificationHub has been retired in favor of Server-Sent Events.
// Real-time notifications now flow through SseNotificationService (see
// EventAggregator.core.cs) and the NotificationController's
// GET api/Notification/stream endpoint, so a single Blazor EventSource client
// consumes updates identically from the .NET and Rust API servers.
//
// This file is intentionally left without a type. To restore SignalR, reinstate
// the Hub class here, re-add builder.Services.AddSignalR() and
// app.MapHub<NotificationHub>("/notificationHub") in Program.cs, and point the
// EventAggregator back at IHubContext.
// </auto-generated>
