// <auto-generated>
// Rust port of Workflow.core.cs. Enumerated types backing the core.workflow_type
// and core.on_failure lookup tables, with description <-> value conversions.
// </auto-generated>

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum WorkflowType {
    Folder = 1,
    Process = 2,
}

impl WorkflowType {
    pub fn description(self) -> &'static str {
        match self {
            WorkflowType::Folder => "Folder",
            WorkflowType::Process => "Process",
        }
    }

    pub fn from_description(description: &str) -> Option<Self> {
        match description.to_ascii_lowercase().as_str() {
            "folder" => Some(WorkflowType::Folder),
            "process" => Some(WorkflowType::Process),
            _ => None,
        }
    }

    pub fn from_i64(value: i64) -> Option<Self> {
        match value {
            1 => Some(WorkflowType::Folder),
            2 => Some(WorkflowType::Process),
            _ => None,
        }
    }
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum OnFailureAction {
    Stop = 1,
    Continue = 2,
}

impl OnFailureAction {
    pub fn description(self) -> &'static str {
        match self {
            OnFailureAction::Stop => "Stop",
            OnFailureAction::Continue => "Continue",
        }
    }

    pub fn from_description(description: &str) -> Option<Self> {
        match description.to_ascii_lowercase().as_str() {
            "stop" => Some(OnFailureAction::Stop),
            "continue" => Some(OnFailureAction::Continue),
            _ => None,
        }
    }

    pub fn from_i64(value: i64) -> Option<Self> {
        match value {
            1 => Some(OnFailureAction::Stop),
            2 => Some(OnFailureAction::Continue),
            _ => None,
        }
    }
}
