// <auto-generated>
// Rust port of BaseLogic.core.cs. The .NET base class was an empty marker;
// here it also hosts the shared error type for the logic layer.
// </auto-generated>

use persist::PersistError;

/// Marker base for generated logic types (parity with the .NET BaseLogic).
pub struct BaseLogic;

/// Error surface for the logic layer: authorization, persistence, and (future)
/// event-script failures.
#[derive(Debug)]
pub enum LogicError {
    Unauthorized(String),
    Persist(PersistError),
    Event(String),
}

impl std::fmt::Display for LogicError {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            LogicError::Unauthorized(m) => write!(f, "unauthorized: {}", m),
            LogicError::Persist(e) => write!(f, "{}", e),
            LogicError::Event(m) => write!(f, "event error: {}", m),
        }
    }
}

impl std::error::Error for LogicError {}

impl From<PersistError> for LogicError {
    fn from(e: PersistError) -> Self {
        LogicError::Persist(e)
    }
}
