// <auto-generated>
// The single AOP chokepoint. `LogicExec::call` runs the before hooks (logging,
// authorization, and — once wired — pre-event scripts), dispatches to the named
// operation, then runs the after hooks (post-event scripts). This replaces the
// .NET reflective DispatchProxy: instead of reflecting over an interface, each
// logic type implements `LogicDispatch` with a generated `match`.
//
// Access control: `dispatch` requires an `ExecProof`, whose constructor is
// private to this module, so the only way to invoke a logic operation is
// through `LogicExec` (which always runs the hooks) — external code cannot call
// `dispatch` (nor the per-object raw methods, which are `pub(crate)`) directly
// and thereby skip authorization. The explicit `call_unchecked` path is the
// deliberate, named bypass for import/export and tests.
// </auto-generated>

use serde_json::Value;

use crate::base_logic::LogicError;
use crate::logic_context::LogicContext;
use crate::proxy;

/// Capability token proving a call came through `LogicExec`. Unconstructable
/// outside this module (private field).
pub struct ExecProof(());

pub trait LogicDispatch {
    /// PascalCase domain object name, used as the authorization / hook key.
    const DOMAIN: &'static str;

    /// Route `method` to the matching operation. Only reachable with an
    /// `ExecProof`, i.e. through `LogicExec`.
    fn dispatch(
        &self,
        method: &str,
        ctx: &mut LogicContext,
        proof: &ExecProof,
    ) -> Result<Value, LogicError>;
}

pub struct LogicExec;

impl LogicExec {
    /// Authorized entry point: before hooks -> dispatch -> after hooks.
    pub fn call<T: LogicDispatch>(
        target: &T,
        method: &str,
        ctx: &mut LogicContext,
    ) -> Result<Value, LogicError> {
        proxy::initialize();
        let proof = ExecProof(());

        // The `enum` operation is a read-only projection of `select` (it returns
        // id + display-string pairs for dropdowns). The .NET enum endpoint called
        // the proxied `select` logic method, so authorization was keyed on
        // `select` — not `enum`, which is not a seeded operation. Mirror that:
        // authorize and audit `enum` under `select` while the dispatch target
        // still sees the real `enum` method name.
        let hook_method = if method.eq_ignore_ascii_case("enum") {
            "select"
        } else {
            method
        };

        proxy::run_before(T::DOMAIN, hook_method, ctx)?;
        let result = target.dispatch(method, ctx, &proof);
        proxy::run_after(T::DOMAIN, hook_method, ctx, result.as_ref().ok())?;
        result
    }

    /// Bypass the hooks (and therefore authorization). Use only where no
    /// security principal exists (import/export, tests).
    pub fn call_unchecked<T: LogicDispatch>(
        target: &T,
        method: &str,
        ctx: &mut LogicContext,
    ) -> Result<Value, LogicError> {
        let proof = ExecProof(());
        target.dispatch(method, ctx, &proof)
    }

    /// Run an arbitrary closure through the same before/after pipeline (logging,
    /// authorization, events) as a built-in operation. Use this to wrap a
    /// custom operation defined in a user file so it is authorized and audited
    /// under the given (`domain`, `method`) name — without modifying any
    /// generated file.
    pub fn call_with<F>(
        domain: &str,
        method: &str,
        ctx: &mut LogicContext,
        op: F,
    ) -> Result<Value, LogicError>
    where
        F: FnOnce(&mut LogicContext) -> Result<Value, LogicError>,
    {
        proxy::initialize();
        proxy::run_before(domain, method, ctx)?;
        let result = op(ctx);
        proxy::run_after(domain, method, ctx, result.as_ref().ok())?;
        result
    }
}
