// <auto-generated>
// The uniform context that flows through every logic call. It carries the
// record under operation (`transaction`) and free-form `args` (e.g. "id",
// "child_suffix"). Because it threads through LogicExec -> dispatch -> hooks,
// the before/after interceptors (auth, logging, event scripts) all see it.
// </auto-generated>

use std::collections::HashMap;

use common::BaseObject;
use serde_json::Value;

#[derive(Debug, Clone, Default)]
pub struct LogicContext {
    /// The record an operation reads/writes (insert/update/put input; also
    /// receives the persisted row, with its assigned id, on the way back).
    pub transaction: BaseObject,
    /// Scalar arguments for the operation.
    pub args: HashMap<String, Value>,
}

impl LogicContext {
    pub fn new() -> Self {
        LogicContext::default()
    }

    /// Context for a record-carrying op (insert / put / update).
    pub fn for_record(transaction: BaseObject) -> Self {
        LogicContext { transaction, args: HashMap::new() }
    }

    /// Context for an id-keyed op (get / view / history / delete).
    pub fn for_id(id: i64) -> Self {
        let mut ctx = LogicContext::default();
        ctx.set_arg("id", Value::from(id));
        ctx
    }

    pub fn set_arg(&mut self, key: &str, value: Value) {
        self.args.insert(key.to_string(), value);
    }

    pub fn arg_i64(&self, key: &str) -> i64 {
        self.args.get(key).and_then(|v| v.as_i64()).unwrap_or_default()
    }

    pub fn arg_str(&self, key: &str) -> String {
        self.args
            .get(key)
            .and_then(|v| v.as_str())
            .map(|s| s.to_string())
            .unwrap_or_default()
    }

    /// The operation's id: the `id` arg if present, else the transaction's id.
    pub fn id(&self) -> i64 {
        if let Some(v) = self.args.get("id").and_then(|v| v.as_i64()) {
            return v;
        }
        self.transaction.get("id").as_i64().unwrap_or_default()
    }
}
