// <auto-generated>
// Rust port of Proxy.core.cs (interception registry).
//
// .NET used a reflection-based DispatchProxy to intercept every interface
// method. Rust has no reflection, so interception is centralised in
// `LogicExec::call` (see logic_exec.core.rs), which runs these before/after
// hooks around a generated `dispatch`. The hooks receive the full
// `LogicContext`, so authorization, logging, and (once wired) the pre/post
// event-service scripts all have access to the record + args under operation.
// </auto-generated>

use std::sync::{Mutex, Once, OnceLock};

use common::Logger;
use serde_json::Value;

use crate::base_logic::LogicError;
use crate::logic_context::LogicContext;
use crate::op_role_member_logic::OpRoleMemberLogic;

/// A before hook: (domain_obj, method_name, ctx); may veto with an error.
pub type BeforeAction =
    Box<dyn Fn(&str, &str, &mut LogicContext) -> Result<(), LogicError> + Send + Sync>;
/// An after hook: (domain_obj, method_name, ctx, result); may surface an error.
pub type AfterAction =
    Box<dyn Fn(&str, &str, &mut LogicContext, Option<&Value>) -> Result<(), LogicError> + Send + Sync>;

struct Registry {
    before: Vec<BeforeAction>,
    after: Vec<AfterAction>,
}

fn registry() -> &'static Mutex<Registry> {
    static REG: OnceLock<Mutex<Registry>> = OnceLock::new();
    REG.get_or_init(|| Mutex::new(Registry { before: Vec::new(), after: Vec::new() }))
}

/// Thread-safe registry of interception hooks (parity with ProxyAction).
pub struct ProxyAction;

impl ProxyAction {
    pub fn add_before_action(action: BeforeAction) {
        registry().lock().unwrap().before.push(action);
    }

    pub fn add_after_action(action: AfterAction) {
        registry().lock().unwrap().after.push(action);
    }
}

/// Run all before hooks; the first error short-circuits (parity with throw).
pub fn run_before(domain_obj: &str, method: &str, ctx: &mut LogicContext) -> Result<(), LogicError> {
    let reg = registry().lock().unwrap();
    for action in reg.before.iter() {
        action(domain_obj, method, ctx)?;
    }
    Ok(())
}

/// Run all after hooks; the first error short-circuits.
pub fn run_after(
    domain_obj: &str,
    method: &str,
    ctx: &mut LogicContext,
    result: Option<&Value>,
) -> Result<(), LogicError> {
    let reg = registry().lock().unwrap();
    for action in reg.after.iter() {
        action(domain_obj, method, ctx, result)?;
    }
    Ok(())
}

/// Install the default hooks exactly once per process (parity with
/// Proxy.Initialize + ProxyCallbackInitializer.Initialize).
pub fn initialize() {
    static INIT: Once = Once::new();
    INIT.call_once(|| {
        // Logging before action.
        ProxyAction::add_before_action(Box::new(|domain_obj, method, _ctx| {
            Logger::info(format!("Invoking {}.{}.", domain_obj, method));
            Ok(())
        }));

        // Authorization before action.
        ProxyAction::add_before_action(Box::new(|domain_obj, method, _ctx| {
            let user = OpRoleMemberLogic::current_user();
            Logger::debug(format!(
                "Checking {} authorization for {}.{}.",
                user, domain_obj, method
            ));
            match OpRoleMemberLogic::authorized(domain_obj, method) {
                Ok(true) => Ok(()),
                Ok(false) => Err(LogicError::Unauthorized(format!(
                    "Principal {} is not authorized for {}.{}.",
                    user, domain_obj, method
                ))),
                Err(e) => Err(LogicError::Persist(e)),
            }
        }));

        // Logging after action.
        ProxyAction::add_after_action(Box::new(|_domain_obj, method, _ctx, _result| {
            Logger::info(format!("After invoking {}.", method));
            Ok(())
        }));

        // Real-time notification after action: on a data change, publish the
        // object so the SSE layer can push it to subscribed web clients (parity
        // with the .NET NotificationRegistrar, which published on insert/update).
        // `publish` returns immediately and does its HTTP fan-out on a background
        // thread, so it never blocks the hook chain or holds the registry lock.
        ProxyAction::add_after_action(Box::new(|domain_obj, method, ctx, result| {
            if matches!(method, "insert" | "update" | "put") {
                let id = ctx.transaction.get("id").as_i64().unwrap_or_default();
                let json_data = result
                    .map(|v| v.to_string())
                    .unwrap_or_else(|| ctx.transaction.to_json());
                crate::notification::publish(domain_obj, id, json_data);
            }
            Ok(())
        }));

        // TODO: pre/post event-service hooks. Now that the hooks carry the
        // LogicContext, an event hook can build an EventContext from
        // `ctx.transaction` and run scripts via the `script` crate's ScriptHost.
        // Pending the callback-registry indirection (script depends on logic).
    });
}
