// <auto-generated>
// New in the Rust port: in .NET the ADO.NET DbConnection/DbCommand/DbDataReader
// types supplied connectivity for free. Rust needs an explicit thin wrapper.
//
// This wraps the synchronous `postgres` driver (matching the .NET synchronous
// persistence API). A connection is opened per operation from the named data
// source, exactly as the .NET layer did via provider.CreateConnection. SQL
// Server connectivity (tiberius) is async-only and is deferred; the
// DatabaseProvider trait still formats SQL for both dialects.
// </auto-generated>

use std::collections::HashMap;

use common::Config;
use serde_json::Value;

/// A single database row, column name -> JSON value. Mirrors the shape the
/// generated domain accessors expect (timestamps / decimals / uuids are stored
/// as strings so they round-trip through the typed getters).
pub type Row = HashMap<String, Value>;

#[derive(Debug)]
pub enum PersistError {
    Unsupported(String),
    Db(String),
}

impl std::fmt::Display for PersistError {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            PersistError::Unsupported(m) => write!(f, "unsupported: {}", m),
            PersistError::Db(m) => write!(f, "db error: {}", m),
        }
    }
}

impl std::error::Error for PersistError {}

impl From<postgres::Error> for PersistError {
    fn from(e: postgres::Error) -> Self {
        // `postgres::Error`'s own Display is just "db error" — the useful detail
        // (SQLSTATE + server message, e.g. column / type / constraint) lives in
        // the embedded DbError or the source chain. Surface it.
        if let Some(db) = e.as_db_error() {
            return PersistError::Db(format!("{}: {}", db.code().code(), db.message()));
        }
        match std::error::Error::source(&e) {
            Some(src) => PersistError::Db(format!("{}: {}", e, src)),
            None => PersistError::Db(e.to_string()),
        }
    }
}

pub struct DbConnection {
    client: postgres::Client,
}

impl DbConnection {
    /// Open a connection for the named data source (reads ~/.<ns>.json).
    pub fn open(connection_name: &str) -> Result<Self, PersistError> {
        let db_type = Config::db_type(connection_name);
        match db_type.as_str() {
            "postgresql" | "pgsql" => {
                let conn_str = Config::db_connection_for(connection_name);
                let client = postgres::Client::connect(&conn_str, postgres::NoTls)?;
                Ok(DbConnection { client })
            }
            other => Err(PersistError::Unsupported(format!(
                "database type '{}' for connection '{}' (only PostgreSQL is wired up)",
                other, connection_name
            ))),
        }
    }

    /// Run a query and return all rows as column-value maps.
    pub fn query(&mut self, sql: &str) -> Result<Vec<Row>, PersistError> {
        let pg_rows = self.client.query(sql, &[])?;
        Ok(pg_rows.iter().map(row_to_map).collect())
    }

    /// Run a non-query statement, returning affected row count.
    pub fn execute(&mut self, sql: &str) -> Result<u64, PersistError> {
        Ok(self.client.execute(sql, &[])?)
    }
}

/// Convert a postgres Row to a column-value map. Temporal / decimal / uuid
/// columns are stringified to match the generated typed accessors.
fn row_to_map(row: &postgres::Row) -> Row {
    let mut map: Row = HashMap::new();
    for (i, col) in row.columns().iter().enumerate() {
        let name = col.name().to_string();
        let value = pg_value_to_json(row, i, &name, col.type_().name());
        map.insert(name, value);
    }
    map
}

fn pg_value_to_json(row: &postgres::Row, i: usize, col_name: &str, type_name: &str) -> Value {
    // A genuine deserialization / type-mapping failure panics (see `read`): at
    // this stage a loud crash is preferred over a silently-Null'd column. A SQL
    // NULL still maps to Value::Null (that is not an error). Temporal / decimal /
    // uuid columns are stringified to match the generated typed accessors; a
    // `date` becomes a midnight timestamp string so it round-trips through the
    // domain's NaiveDateTime getter.
    const TS_FMT: &str = "%Y-%m-%dT%H:%M:%S%.f";
    match type_name {
        "int2" => num(read::<i16>(row, i, col_name, type_name).map(|v| v as i64)),
        "int4" => num(read::<i32>(row, i, col_name, type_name).map(|v| v as i64)),
        "int8" => num(read::<i64>(row, i, col_name, type_name)),
        "float4" => read::<f32>(row, i, col_name, type_name)
            .map(|v| serde_json::json!(v as f64))
            .unwrap_or(Value::Null),
        "float8" => read::<f64>(row, i, col_name, type_name)
            .map(|v| serde_json::json!(v))
            .unwrap_or(Value::Null),
        "bool" => read::<bool>(row, i, col_name, type_name)
            .map(Value::Bool)
            .unwrap_or(Value::Null),
        "numeric" => str_val(
            read::<rust_decimal::Decimal>(row, i, col_name, type_name).map(|d| d.to_string()),
        ),
        "date" => str_val(
            read::<chrono::NaiveDate>(row, i, col_name, type_name)
                .and_then(|d| d.and_hms_opt(0, 0, 0))
                .map(|dt| dt.format(TS_FMT).to_string()),
        ),
        "timestamp" => str_val(
            read::<chrono::NaiveDateTime>(row, i, col_name, type_name)
                .map(|t| t.format(TS_FMT).to_string()),
        ),
        "timestamptz" => str_val(
            read::<chrono::DateTime<chrono::Utc>>(row, i, col_name, type_name)
                .map(|t| t.naive_utc().format(TS_FMT).to_string()),
        ),
        "uuid" => str_val(read::<uuid::Uuid>(row, i, col_name, type_name).map(|u| u.to_string())),
        "json" | "jsonb" => read::<Value>(row, i, col_name, type_name).unwrap_or(Value::Null),
        // varchar / text / bpchar / name / char and anything else -> string
        _ => str_val(read::<String>(row, i, col_name, type_name)),
    }
}

/// Read an optional typed value, panicking with full context on a real
/// deserialization error. A SQL NULL returns None and is not treated as an
/// error.
fn read<'a, T: postgres::types::FromSql<'a>>(
    row: &'a postgres::Row,
    i: usize,
    col_name: &str,
    type_name: &str,
) -> Option<T> {
    row.try_get::<_, Option<T>>(i).unwrap_or_else(|e| {
        panic!(
            "error deserializing column {} '{}' (postgres type '{}') as {}: {}",
            i,
            col_name,
            type_name,
            std::any::type_name::<T>(),
            e
        )
    })
}

fn num(v: Option<i64>) -> Value {
    v.map(Value::from).unwrap_or(Value::Null)
}

fn str_val(v: Option<String>) -> Value {
    v.map(Value::String).unwrap_or(Value::Null)
}
