// <auto-generated>
// Import strategy: unlike the audited/basic strategies, insert does NOT call
// DBPersist::identity() to mint a new pk. The import tool's source data file
// is expected to already carry the real `id` (and, for audited tables,
// `txn_id`) values, and the whole point of running through this provider is
// to preserve them verbatim instead of letting the DB assign new ones.
//
// Selected by DBPersist when import mode is active (DBPersist::set_import_mode),
// regardless of the object's `is_audited` flag — see db_persist.core.rs.
// </auto-generated>

use common::DomainObject;
use serde_json::Value;

use crate::db_connection::PersistError;
use crate::db_persist::{json_now, user_name, DBPersist};
use crate::db_persist_basic;

/// Like `Value::as_i64`, but also accepts a numeric string — CSV-sourced
/// fields land here as `Value::String` (see the import tool), unlike values
/// that round-tripped through a DB row, which are already `Value::Number`.
fn as_i64_lenient(v: &Value) -> i64 {
    match v {
        Value::Number(n) => n.as_i64().unwrap_or_default(),
        Value::String(s) => s.trim().parse::<i64>().unwrap_or_default(),
        _ => 0,
    }
}

pub fn insert<T: DomainObject>(obj: &mut T, connection_name: &str) -> Result<i64, PersistError> {
    let id = as_i64_lenient(&obj.base().get("id"));
    if id == 0 {
        return Err(PersistError::Db(format!(
            "{}: import insert requires a pre-assigned 'id' value in the source data; none was provided.",
            obj.base().domain_name
        )));
    }

    // Preserve an explicit txn_id from the source data (audited tables); fall
    // back to id, matching the audited strategy's convention for a fresh row.
    let txn_id = as_i64_lenient(&obj.base().get("txn_id"));
    obj.base_mut().set("txn_id", Value::from(if txn_id != 0 { txn_id } else { id }));
    obj.base_mut().set("is_active", Value::from(1));
    obj.base_mut().set("created_by", Value::String(user_name()));
    obj.base_mut().set("last_updated", json_now());
    obj.base_mut().set("last_updated_by", Value::String(user_name()));

    let table = obj.base().table_name.clone();
    let sql = DBPersist::insert_sql(obj, &table, connection_name);
    DBPersist::exec_cmd(&sql, connection_name)?;

    Ok(id)
}

pub fn update<T: DomainObject>(obj: &mut T, connection_name: &str) -> Result<(), PersistError> {
    // Imports only ever insert; update is implemented for contract parity with
    // the audit/basic strategies and behaves like an in-place basic update
    // (no new version row, no identity generation).
    db_persist_basic::update(obj, connection_name)
}
