// <auto-generated>
// Rust port of IDBPersist.core.cs.
//
// The .NET interface was dispatched through a `dyn IDBPersist` reference chosen
// by `isAudited`. Rust trait objects can't carry generic methods, so the
// strategies (audit / basic / import) live as free functions in their own
// modules and `DBPersist` selects between them at call time — normally on
// `isAudited`, or unconditionally to `import` while import mode is active
// (see `DBPersist::set_import_mode`). This trait documents the contract those
// functions satisfy and is implemented by each strategy unit.
// </auto-generated>

use common::DomainObject;

use crate::db_connection::PersistError;

pub trait IDbPersist {
    fn insert<T: DomainObject>(obj: &mut T, connection_name: &str) -> Result<i64, PersistError>;
    fn update<T: DomainObject>(obj: &mut T, connection_name: &str) -> Result<(), PersistError>;
}
