// <auto-generated>
// Rust port of IDBPersist.core.cs.
//
// The .NET interface was dispatched through a `dyn IDBPersist` reference chosen
// by `isAudited`. Rust trait objects can't carry generic methods, so the two
// strategies (audit / basic) live as free functions in their own modules and
// `DBPersist` selects between them at call time. This trait documents the
// contract those functions satisfy and is implemented by both strategy units.
// </auto-generated>

use common::DomainObject;

use crate::db_connection::PersistError;

pub trait IDbPersist {
    fn insert<T: DomainObject>(obj: &mut T, connection_name: &str) -> Result<i64, PersistError>;
    fn update<T: DomainObject>(obj: &mut T, connection_name: &str) -> Result<(), PersistError>;
}
