// <auto-generated>
// Crate root for the `persist` library. Generated filenames keep the `.core`
// infix, so modules are wired in with explicit #[path].
// </auto-generated>

#[path = "db_connection.core.rs"]
pub mod db_connection;
#[path = "i_db_persist.core.rs"]
pub mod i_db_persist;
#[path = "db_persist.core.rs"]
pub mod db_persist;
#[path = "db_persist_audit.core.rs"]
pub mod db_persist_audit;
#[path = "db_persist_basic.core.rs"]
pub mod db_persist_basic;

pub use db_connection::{DbConnection, PersistError, Row};
pub use db_persist::DBPersist;
pub use i_db_persist::IDbPersist;
