// <auto-generated>
// Column / class metadata. Rust has no runtime attribute reflection, so the
// generator emits this metadata explicitly. The .NET ColumnInfoAttribute /
// ClassInfoAttribute become plain structs that the persistence and API layers
// read from each domain type's `columns()` / `class_label()` associated fns.
// </auto-generated>

use std::collections::HashMap;

use serde_json::Value;

/// Describes a single column on a domain object. Mirrors ColumnInfoAttribute.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct ColumnInfo {
    /// snake_case column name (e.g. `org_id`).
    pub name: &'static str,
    /// Human readable label.
    pub label: &'static str,
    /// Referenced PascalCase domain object (for FK columns), else "".
    pub fk_object: &'static str,
    /// FK kind: "enum", "parent", "map" or "".
    pub fk_type: &'static str,
    /// Referenced table name, else "".
    pub fk_table: &'static str,
    /// Referenced lowercase variable name, else "".
    pub fk_var: &'static str,
    /// Lowercase PostgreSQL data type (e.g. `numeric`, `varchar`, `bigint`).
    pub data_type: &'static str,
}

impl ColumnInfo {
    pub const fn new(
        name: &'static str,
        label: &'static str,
        fk_object: &'static str,
        fk_type: &'static str,
        fk_table: &'static str,
        fk_var: &'static str,
        data_type: &'static str,
    ) -> Self {
        Self { name, label, fk_object, fk_type, fk_table, fk_var, data_type }
    }

    pub fn is_foreign_key(&self) -> bool {
        !self.fk_object.is_empty()
    }

    /// True for numeric column types whose values are stored as strings (to
    /// preserve precision) but should serialize to the API as JSON numbers.
    pub fn is_string_numeric(&self) -> bool {
        matches!(self.data_type, "numeric" | "decimal" | "money")
    }

    /// True for date/time column types. An empty string is not valid input
    /// for these on either backing database (Postgres error 22007, "invalid
    /// input syntax for type timestamp"), unlike a plain varchar column where
    /// an empty string is a legitimate value -- so callers building INSERT/
    /// UPDATE SQL should coerce "" to NULL only for columns where this is
    /// true. Matched by substring rather than an exact list so this also
    /// covers variants like "timestamp without time zone", "timestamptz",
    /// "datetime2", "smalldatetime".
    pub fn is_temporal(&self) -> bool {
        self.data_type.contains("date") || self.data_type.contains("time")
    }
}

/// Serialize an object's data map to JSON, coercing string-stored numeric
/// columns (`numeric`/`decimal`/`money`) to JSON numbers so the wire format
/// matches the .NET API (which serializes decimals as numbers). Columns not in
/// `columns` (e.g. synthesized view columns) pass through unchanged.
pub fn to_typed_json(data: &HashMap<String, Value>, columns: &[ColumnInfo]) -> Value {
    let mut map = serde_json::Map::with_capacity(data.len());
    for (key, value) in data {
        let coerced = match columns.iter().find(|c| c.name == key) {
            Some(col) if col.is_string_numeric() => coerce_number(value),
            _ => value.clone(),
        };
        map.insert(key.clone(), coerced);
    }
    Value::Object(map)
}

fn coerce_number(value: &Value) -> Value {
    match value {
        Value::String(s) => s
            .parse::<f64>()
            .ok()
            .and_then(serde_json::Number::from_f64)
            .map(Value::Number)
            .unwrap_or_else(|| value.clone()),
        other => other.clone(),
    }
}

/// Class-level metadata. Mirrors ClassInfoAttribute.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct ClassInfo {
    pub label: &'static str,
}

impl ClassInfo {
    pub const fn new(label: &'static str) -> Self {
        Self { label }
    }
}
