// <auto-generated>
// Auth0 support shared by every Rust server (api/scheduler/scriptagent):
//
//   - Inbound: validate an RS256 JWT on a request this process received,
//     against ITS OWN audience (see `Config::auth0_settings`). Used for both
//     user JWTs (the API, browser-facing) and M2M JWTs (all three servers,
//     service-to-service -- see docs/auth0-m2m.md).
//   - Outbound: fetch (and cache) an Auth0 client-credentials token to call
//     another service (see `Config::m2m_client_settings`). Used by the API
//     (calling the Scheduler) and the Scheduler (calling a ScriptAgent).
//     ScriptAgent never calls out, so it never needs this half.
//
// Domain/audiences/M2M client credentials are all read at runtime from this
// application's own ~/.<namespace>.json, not baked in at generation time --
// see common::config::NamespaceConfig / Config::auth0_settings /
// Config::m2m_client_settings for why (one jumpstart install generates many
// applications, so per-app secrets don't belong in the generator's own
// ~/.jumpstart.json).
//
// Mirrors the .NET AddJwtBearer(...) pipeline plus the M2MTokenProvider /
// M2MAuthHandler pair (see docs/auth0-setup.md, docs/auth0-m2m.md).
// </auto-generated>
#![allow(dead_code)]

use std::collections::HashMap;
use std::sync::{Mutex, OnceLock};
use std::time::{Duration, Instant};

use jsonwebtoken::{decode, decode_header, Algorithm, DecodingKey, Validation};
use serde::Deserialize;
use serde_json::Value;

use crate::config::{Config, M2MClientSettings};

// ── Inbound: validate a bearer token against this service's own audience ───

/// Outcome of authenticating one inbound request for a given service
/// (`"api"`, `"scheduler"`, or `"scriptagent"`).
pub enum AuthOutcome {
    /// This service has no Auth0 audience configured; caller should fall
    /// back to its pre-Auth0 behavior (e.g. the API's X-User header, or
    /// simply allowing the request through, for Scheduler/ScriptAgent).
    Unconfigured,
    /// A valid JWT was presented. Carries the principal: the email/`sub`
    /// claim for a user token, or the client id for an M2M
    /// client-credentials token (which has neither email nor `sub`).
    Authenticated(String),
    /// Auth0 is configured but the request carried no bearer token at all.
    Missing,
    /// A bearer token was presented but failed validation (bad signature,
    /// expired, wrong audience/issuer, unknown signing key, ...). Carries a
    /// human-readable reason for logging; callers should reject with 401.
    Invalid(String),
}

/// Authenticate one inbound request for `service` (`"api"` | `"scheduler"` |
/// `"scriptagent"`) against that service's own configured Auth0 audience.
pub fn authenticate_inbound(service: &str, auth_header: Option<&str>) -> AuthOutcome {
    let settings = match Config::auth0_settings(service) {
        Some(s) => s,
        None => return AuthOutcome::Unconfigured,
    };

    let token = match auth_header.and_then(strip_bearer_prefix) {
        Some(t) if !t.is_empty() => t,
        _ => return AuthOutcome::Missing,
    };

    match validate(&settings.domain, &settings.audience, token) {
        Ok(claims) => {
            // User tokens carry an email (added by the Post-Login Action in
            // docs/auth0-setup.md step 7) or at least `sub`; M2M
            // client-credentials tokens carry neither, but do carry the
            // client id in `azp` (Auth0's "authorized party" claim; `client_id`
            // is also accepted as a fallback).
            let principal = claim_str(&claims, "https://claims/email")
                .or_else(|| claim_str(&claims, "email"))
                .or_else(|| claim_str(&claims, "sub"))
                .or_else(|| claim_str(&claims, "azp"))
                .or_else(|| claim_str(&claims, "client_id"));
            match principal {
                Some(p) => AuthOutcome::Authenticated(p),
                None => AuthOutcome::Invalid("token has no email/sub/azp claim".to_string()),
            }
        }
        Err(e) => AuthOutcome::Invalid(e),
    }
}

fn validate(domain: &str, audience: &str, token: &str) -> Result<Value, String> {
    let header = decode_header(token).map_err(|e| format!("malformed token header: {}", e))?;
    let kid = header.kid.ok_or_else(|| "token header missing 'kid'".to_string())?;

    // Try the cached JWKS first; on a cache miss, force one refresh (covers
    // Auth0 signing-key rotation) before giving up.
    let mut keys = jwks(domain, false)?;
    if !keys.iter().any(|k| k.kid == kid) {
        keys = jwks(domain, true)?;
    }
    let jwk = keys
        .iter()
        .find(|k| k.kid == kid)
        .ok_or_else(|| format!("no signing key found for kid '{}'", kid))?;
    if jwk.kty != "RSA" {
        return Err(format!("unsupported signing key type '{}'", jwk.kty));
    }

    let decoding_key = DecodingKey::from_rsa_components(&jwk.n, &jwk.e)
        .map_err(|e| format!("bad signing key: {}", e))?;

    let mut validation = Validation::new(Algorithm::RS256);
    validation.set_audience(&[audience]);
    validation.set_issuer(&[format!("https://{}/", domain)]);

    decode::<Value>(token, &decoding_key, &validation)
        .map(|data| data.claims)
        .map_err(|e| format!("token validation failed: {}", e))
}

fn strip_bearer_prefix(header: &str) -> Option<&str> {
    header
        .strip_prefix("Bearer ")
        .or_else(|| header.strip_prefix("bearer "))
        .map(str::trim)
}

fn claim_str(claims: &Value, key: &str) -> Option<String> {
    claims.get(key).and_then(Value::as_str).map(str::to_string)
}

// ── JWKS cache, keyed by Auth0 domain (defensive -- in practice a process
// validates against a single tenant, but nothing stops several) ────────────

#[derive(Debug, Clone, Deserialize)]
struct Jwks {
    keys: Vec<Jwk>,
}

#[derive(Debug, Clone, Deserialize)]
struct Jwk {
    kid: String,
    kty: String,
    n: String,
    e: String,
}

/// How long a fetched JWKS is trusted before being re-fetched on a schedule
/// (Auth0 rotates signing keys infrequently; this just bounds staleness).
const JWKS_TTL: Duration = Duration::from_secs(600);

fn jwks_cache() -> &'static Mutex<HashMap<String, (Instant, Vec<Jwk>)>> {
    static CACHE: OnceLock<Mutex<HashMap<String, (Instant, Vec<Jwk>)>>> = OnceLock::new();
    CACHE.get_or_init(|| Mutex::new(HashMap::new()))
}

/// Fetch (or return the cached copy of) `domain`'s signing keys from
/// `https://{domain}/.well-known/jwks.json`. Pass `force_refresh` to bypass
/// the TTL -- used once when a token's `kid` isn't found in the cache, so a
/// freshly rotated Auth0 signing key is picked up without waiting for the
/// next scheduled refresh.
fn jwks(domain: &str, force_refresh: bool) -> Result<Vec<Jwk>, String> {
    {
        let cache = jwks_cache().lock().unwrap();
        if !force_refresh {
            if let Some((fetched_at, keys)) = cache.get(domain) {
                if fetched_at.elapsed() < JWKS_TTL {
                    return Ok(keys.clone());
                }
            }
        }
    }

    let url = format!("https://{}/.well-known/jwks.json", domain);
    let body_str = ureq::get(&url)
        .call()
        .map_err(|e| format!("JWKS fetch from {} failed: {}", url, e))?
        .into_string()
        .map_err(|e| format!("JWKS response from {} unreadable: {}", url, e))?;
    let body: Jwks = serde_json::from_str(&body_str)
        .map_err(|e| format!("JWKS response from {} not valid JSON: {}", url, e))?;

    jwks_cache()
        .lock()
        .unwrap()
        .insert(domain.to_string(), (Instant::now(), body.keys.clone()));
    Ok(body.keys)
}

// ── Outbound: M2M client-credentials tokens for service-to-service calls ───

#[derive(Debug, Clone, Deserialize)]
struct TokenResponse {
    access_token: String,
    expires_in: u64,
}

struct CachedToken {
    token: String,
    expires_at: Instant,
}

impl CachedToken {
    fn is_valid(&self) -> bool {
        Instant::now() < self.expires_at
    }
}

fn m2m_cache() -> &'static Mutex<HashMap<String, CachedToken>> {
    static CACHE: OnceLock<Mutex<HashMap<String, CachedToken>>> = OnceLock::new();
    CACHE.get_or_init(|| Mutex::new(HashMap::new()))
}

/// Get a valid Bearer token for calling `target_service` (`"scheduler"` or
/// `"scriptagent"`), fetching (and caching) a fresh Auth0 client-credentials
/// token if needed. Returns `Ok(None)` if no `m2m_clients` entry is
/// configured for `target_service` in `~/.<namespace>.json` -- callers
/// should then make the call unauthenticated, matching the .NET
/// `M2MTokenProvider.Instance == null` fallback (useful for local
/// development without Auth0). Returns `Err` only on an actual fetch
/// failure (network error, bad credentials, ...); callers should log and
/// still attempt the call, same as the .NET provider swallowing the error.
pub fn m2m_token(target_service: &str) -> Result<Option<String>, String> {
    let settings = match Config::m2m_client_settings(target_service) {
        Some(s) => s,
        None => return Ok(None),
    };

    if let Some(cached) = m2m_cache().lock().unwrap().get(target_service) {
        if cached.is_valid() {
            return Ok(Some(cached.token.clone()));
        }
    }

    let response = fetch_m2m_token(&settings)?;
    // Refresh 60s before actual expiry, matching the .NET M2MTokenProvider.
    let ttl = Duration::from_secs(response.expires_in.saturating_sub(60));
    let access_token = response.access_token.clone();
    m2m_cache().lock().unwrap().insert(
        target_service.to_string(),
        CachedToken {
            token: response.access_token,
            expires_at: Instant::now() + ttl,
        },
    );
    Ok(Some(access_token))
}

fn fetch_m2m_token(settings: &M2MClientSettings) -> Result<TokenResponse, String> {
    let payload = serde_json::json!({
        "grant_type": "client_credentials",
        "client_id": settings.client_id,
        "client_secret": settings.client_secret,
        "audience": settings.audience,
    })
    .to_string();

    let body_str = ureq::post(&settings.token_endpoint)
        .set("Content-Type", "application/json")
        .send_string(&payload)
        .map_err(|e| format!("M2M token fetch from {} failed: {}", settings.token_endpoint, e))?
        .into_string()
        .map_err(|e| {
            format!(
                "M2M token response from {} unreadable: {}",
                settings.token_endpoint, e
            )
        })?;

    serde_json::from_str(&body_str).map_err(|e| {
        format!(
            "M2M token response from {} not valid JSON: {}",
            settings.token_endpoint, e
        )
    })
}
