// <auto-generated>
// Rust port of BaseObject.core.cs.
//
// The .NET BaseObject is a Dictionary<string, object> with reflection-driven
// typed properties. Rust has no runtime reflection, so we keep the same
// dictionary-backed design (a HashMap<String, serde_json::Value>) and let the
// generated domain types provide statically typed accessors over it. This keeps
// the persistence contract identical: every value round-trips through `data`.
// </auto-generated>

use std::collections::HashMap;
use serde_json::Value;

use crate::ColumnInfo;

/// Dynamic, dictionary-backed base for every domain object.
#[derive(Debug, Clone, Default)]
pub struct BaseObject {
    /// Live column values, keyed by snake_case column name.
    pub data: HashMap<String, Value>,
    /// Default values applied when a key is absent.
    pub defaults: HashMap<String, Value>,
    pub domain_name: String,
    pub table_name: String,
    pub table_base_name: String,
    pub schema_name: String,
    pub audit_table_name: String,
    pub is_audited: bool,
    /// Real World Key column names.
    pub rwk: Vec<String>,
}

impl BaseObject {
    pub fn new() -> Self {
        BaseObject { is_audited: true, ..Default::default() }
    }

    /// Read a value, falling back to the registered default (or Null).
    pub fn get(&self, key: &str) -> Value {
        if let Some(v) = self.data.get(key) {
            v.clone()
        } else if let Some(d) = self.defaults.get(key) {
            d.clone()
        } else {
            Value::Null
        }
    }

    /// Write a value, skipping no-op writes (mirrors the C# indexer guard).
    pub fn set(&mut self, key: &str, value: Value) {
        match self.data.get(key) {
            Some(existing) if *existing == value => {}
            _ => {
                self.data.insert(key.to_string(), value);
            }
        }
    }

    pub fn contains_key(&self, key: &str) -> bool {
        self.data.contains_key(key)
    }

    pub fn get_rwk(&self) -> &[String] {
        &self.rwk
    }

    /// Space-joined RWK values; `_id` keys are skipped unless `include_id`.
    pub fn get_rwk_string(&self, include_id: bool) -> String {
        self.rwk
            .iter()
            .filter(|c| include_id || !c.ends_with("_id"))
            .map(|c| match self.get(c) {
                Value::String(s) => s,
                Value::Null => String::new(),
                other => other.to_string(),
            })
            .collect::<Vec<_>>()
            .join(" ")
    }

    /// Pretty-printed JSON of the live data (mirrors ToString()).
    pub fn to_json(&self) -> String {
        serde_json::to_string_pretty(&self.data)
            .unwrap_or_else(|e| format!("BaseObject(Serialization error: {})", e))
    }
}

/// Behaviour shared by every generated domain object.
pub trait DomainObject {
    fn base(&self) -> &BaseObject;
    fn base_mut(&mut self) -> &mut BaseObject;

    /// Column metadata for this type (replaces attribute reflection).
    fn columns() -> Vec<ColumnInfo>
    where
        Self: Sized;

    /// Class-level display label.
    fn class_label() -> &'static str
    where
        Self: Sized;

    /// Populate names, defaults and rwk on the backing BaseObject.
    fn initialize(&mut self);
}
