// <auto-generated>
// Rust port of IDatabaseProvider.cs.
//
// The .NET interface mixed ADO.NET connection/command construction with SQL
// string formatting. Connection handling in Rust belongs to the persistence
// layer (sqlx / tokio-postgres / tiberius), so this trait keeps the portable,
// dialect-specific *SQL text* formatting that the query builders rely on.
// </auto-generated>

use serde_json::Value;

pub trait DatabaseProvider: Send + Sync {
    /// SQL that yields the next identity value for a table's sequence.
    fn next_identity_sql(&self, table_name: &str) -> String;

    /// Positional/named placeholder for the Nth (1-based) bind parameter.
    fn format_parameter(&self, index: usize) -> String;

    /// Quote a (possibly schema-qualified) table name for this dialect.
    fn format_table_name(&self, table_name: &str) -> String;

    /// Quote a column name for this dialect.
    fn format_column_name(&self, column_name: &str) -> String;

    /// Render a literal value into SQL (used for static data / debugging).
    fn format_value(&self, value: &Value) -> String;
}

/// Shared literal-rendering helper (single-quote escape, NULL handling).
pub(crate) fn render_value(value: &Value) -> String {
    match value {
        Value::Null => "NULL".to_string(),
        Value::Bool(b) => b.to_string(),
        Value::Number(n) => n.to_string(),
        Value::String(s) => format!("'{}'", s.replace('\'', "''")),
        other => format!("'{}'", other.to_string().replace('\'', "''")),
    }
}
