// <auto-generated>
// Rust port of DatabaseProviderFactory.cs. Resolves and caches a
// DatabaseProvider per named connection, based on the configured db type.
// </auto-generated>

use std::collections::HashMap;
use std::sync::{Arc, Mutex, OnceLock};

use crate::config::Config;
use crate::db_provider::DatabaseProvider;
use crate::postgres_provider::PostgreSQLProvider;
use crate::sqlserver_provider::SqlServerProvider;

type ProviderCache = Mutex<HashMap<String, Arc<dyn DatabaseProvider>>>;

fn cache() -> &'static ProviderCache {
    static CACHE: OnceLock<ProviderCache> = OnceLock::new();
    CACHE.get_or_init(|| Mutex::new(HashMap::new()))
}

pub struct DatabaseProviderFactory;

impl DatabaseProviderFactory {
    /// Create or retrieve a cached provider for the named connection.
    pub fn create_provider(connection_name: &str) -> Arc<dyn DatabaseProvider> {
        let connection_name = if connection_name.is_empty() {
            "default"
        } else {
            connection_name
        };

        let mut cache = cache().lock().unwrap();
        if let Some(p) = cache.get(connection_name) {
            return Arc::clone(p);
        }

        let db_type = Config::db_type(connection_name);
        let provider: Arc<dyn DatabaseProvider> = match db_type.as_str() {
            "postgresql" | "pgsql" => Arc::new(PostgreSQLProvider::new()),
            "sqlserver" | "mssql" => Arc::new(SqlServerProvider::new()),
            other => panic!(
                "Unsupported database type: {} for connection '{}'",
                other, connection_name
            ),
        };

        cache.insert(connection_name.to_string(), Arc::clone(&provider));
        provider
    }

    pub fn clear_provider_cache() {
        cache().lock().unwrap().clear();
    }

    pub fn cache_size() -> usize {
        cache().lock().unwrap().len()
    }

    pub fn remove_provider(connection_name: &str) -> bool {
        cache().lock().unwrap().remove(connection_name).is_some()
    }
}
