// <auto-generated>
// Rust port of EnumHelper.cs. Id + display string pair used to populate
// enum / lookup dropdowns returned from the `/api/<table>/enum` endpoints.
// </auto-generated>

use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct EnumHelper {
    pub id: i64,
    #[serde(rename = "rwkString")]
    pub rwk_string: String,
}

impl EnumHelper {
    pub fn new(id: i64, rwk_string: impl Into<String>) -> Self {
        EnumHelper { id, rwk_string: rwk_string.into() }
    }
}
