// <auto-generated>
// Rust port of JsonHelper.cs.
//
// In .NET this normalised JsonElement values into typed properties via
// reflection. In Rust everything is already a serde_json::Value inside the
// BaseObject map, so the helper focuses on (de)serialising a BaseObject's data
// to/from JSON. Type coercion is handled by the generated typed accessors.
// </auto-generated>

use std::collections::HashMap;

use serde_json::Value;

use crate::base_object::BaseObject;
use crate::logger::Logger;

pub struct JsonHelper;

impl JsonHelper {
    /// Serialise a BaseObject's live data to a JSON string.
    pub fn to_json(obj: &BaseObject) -> String {
        serde_json::to_string(&obj.data).unwrap_or_else(|e| {
            Logger::error(format!("Failed to serialize JSON: {}", e));
            "{}".to_string()
        })
    }

    /// Parse a JSON object string into a column-value map suitable for
    /// loading into a BaseObject's `data`.
    pub fn parse_map(json: &str) -> Option<HashMap<String, Value>> {
        if json.is_empty() {
            return None;
        }
        match serde_json::from_str::<HashMap<String, Value>>(json) {
            Ok(map) => Some(map),
            Err(e) => {
                Logger::error(format!("Failed to deserialize JSON: {}", e));
                None
            }
        }
    }

    /// Load a JSON object string directly into an existing BaseObject.
    pub fn load_into(obj: &mut BaseObject, json: &str) -> bool {
        match Self::parse_map(json) {
            Some(map) => {
                for (k, v) in map {
                    obj.set(&k, v);
                }
                true
            }
            None => false,
        }
    }
}
