// <auto-generated>
// Crate root for the `common` library. Generated filenames keep the `.core`
// infix from the .NET layer, so modules are wired in with explicit #[path].
// </auto-generated>

#[path = "attributes.core.rs"]
pub mod attributes;
#[path = "base_object.core.rs"]
pub mod base_object;
#[path = "config.core.rs"]
pub mod config;
#[path = "logger.core.rs"]
pub mod logger;
#[path = "util.core.rs"]
pub mod util;
#[path = "session_info.core.rs"]
pub mod session_info;
pub mod json_helper;
pub mod enum_helper;
#[path = "db_provider.core.rs"]
pub mod db_provider;
pub mod postgres_provider;
pub mod sqlserver_provider;
pub mod db_provider_factory;
pub mod auth0;

// Flattened re-exports so domain/persist/logic/api can `use common::*`.
pub use attributes::{to_typed_json, ClassInfo, ColumnInfo};
pub use base_object::{BaseObject, DomainObject};
pub use config::{
    Auth0Config, Auth0Settings, Config, DataSourceConfig, M2MClientConfig, M2MClientSettings,
    NamespaceConfig, NAMESPACE,
};
pub use db_provider::DatabaseProvider;
pub use db_provider_factory::DatabaseProviderFactory;
pub use enum_helper::EnumHelper;
pub use json_helper::JsonHelper;
pub use logger::{LogLevel, LogRecord, Logger};
pub use postgres_provider::PostgreSQLProvider;
pub use session_info::SessionInfo;
pub use sqlserver_provider::SqlServerProvider;
pub use util::Util;
