// <auto-generated>
// Rust port of PostgreSQLProvider.cs. PostgreSQL uses positional `$N`
// bind parameters and double-quoted identifiers.
// </auto-generated>

use serde_json::Value;

use crate::db_provider::{render_value, DatabaseProvider};

#[derive(Debug, Default, Clone)]
pub struct PostgreSQLProvider;

impl PostgreSQLProvider {
    pub fn new() -> Self {
        PostgreSQLProvider
    }
}

impl DatabaseProvider for PostgreSQLProvider {
    fn next_identity_sql(&self, table_name: &str) -> String {
        format!("SELECT nextval('{}_identity');", table_name)
    }

    fn format_parameter(&self, index: usize) -> String {
        format!("${}", index)
    }

    fn format_table_name(&self, table_name: &str) -> String {
        if table_name.is_empty() {
            return table_name.to_string();
        }
        table_name
            .split('.')
            .map(|p| format!("\"{}\"", p))
            .collect::<Vec<_>>()
            .join(".")
    }

    fn format_column_name(&self, column_name: &str) -> String {
        format!("\"{}\"", column_name)
    }

    fn format_value(&self, value: &Value) -> String {
        render_value(value)
    }
}
