// <auto-generated>
// Rust port of SessionInfo.core.cs. Thread-safe, process-wide key/value store
// for ambient session data (host, user, OS, ...). The .NET singleton becomes a
// lazily-initialised global guarded by a Mutex.
// </auto-generated>

use std::collections::HashMap;
use std::sync::{Mutex, OnceLock};

fn store() -> &'static Mutex<HashMap<String, String>> {
    static STORE: OnceLock<Mutex<HashMap<String, String>>> = OnceLock::new();
    STORE.get_or_init(|| Mutex::new(HashMap::new()))
}

pub struct SessionInfo;

impl SessionInfo {
    pub fn set_value(key: &str, value: &str) {
        store().lock().unwrap().insert(key.to_string(), value.to_string());
    }

    pub fn get_value(key: &str, default_value: Option<&str>) -> Option<String> {
        store()
            .lock()
            .unwrap()
            .get(key)
            .cloned()
            .or_else(|| default_value.map(|s| s.to_string()))
    }

    pub fn get(key: &str) -> Option<String> {
        store().lock().unwrap().get(key).cloned()
    }

    pub fn has_value(key: &str) -> bool {
        store()
            .lock()
            .unwrap()
            .get(key)
            .map(|v| !v.is_empty())
            .unwrap_or(false)
    }

    pub fn remove_value(key: &str) -> bool {
        store().lock().unwrap().remove(key).is_some()
    }

    pub fn all_keys() -> Vec<String> {
        store().lock().unwrap().keys().cloned().collect()
    }

    pub fn clear_all() {
        store().lock().unwrap().clear();
    }
}
