// <auto-generated>
// Rust port of Util.core.cs. Populates SessionInfo with host/user/OS details
// and exposes the legacy minimum-date helper used by some SQL Server logic.
// </auto-generated>

use chrono::NaiveDateTime;

use crate::session_info::SessionInfo;

pub struct Util;

impl Util {
    /// Populate the process-wide SessionInfo with current environment details.
    pub fn populate_session_info() {
        SessionInfo::set_value("ComputerName", &host_name());
        SessionInfo::set_value("UserName", &user_name());
        SessionInfo::set_value("UserDomain", &user_domain());
        SessionInfo::set_value("CurrentDirectory", &current_dir());
        SessionInfo::set_value("OSName", os_name());
        SessionInfo::set_value("OSVersion", &os_version());
        SessionInfo::set_value("Architecture", arch());
        SessionInfo::set_value(
            "OSAndArchitecture",
            &format!("{} ({})", os_name(), arch()),
        );
    }

    /// Legacy minimum date (1900-01-01 00:00:00) used by some SQL Server logic.
    pub fn min_date_value() -> NaiveDateTime {
        NaiveDateTime::parse_from_str("1900-01-01 00:00:00", "%Y-%m-%d %H:%M:%S")
            .expect("valid constant date")
    }

    /// Current UTC timestamp formatted as a SQL timestamp literal. Matches the
    /// stored-as-string convention used by the domain's NaiveDateTime accessors,
    /// so it round-trips through insert/select unchanged.
    pub fn now_timestamp() -> String {
        chrono::Utc::now()
            .naive_utc()
            .format("%Y-%m-%d %H:%M:%S")
            .to_string()
    }

    /// Current UTC timestamp in ISO 8601 (`T` separator, fractional seconds).
    /// Used on the wire for JSON timestamps so a .NET `DateTime` deserializes it
    /// without a custom format.
    pub fn now_iso8601() -> String {
        chrono::Utc::now()
            .naive_utc()
            .format("%Y-%m-%dT%H:%M:%S%.f")
            .to_string()
    }
}

fn host_name() -> String {
    // The HOSTNAME env var is not exported to child processes on macOS (and
    // often not on Linux either), so query the system directly first and only
    // fall back to the env vars / "unknown".
    #[cfg(unix)]
    {
        if let Some(name) = std::process::Command::new("hostname")
            .output()
            .ok()
            .and_then(|o| String::from_utf8(o.stdout).ok())
            .map(|s| s.trim().to_string())
            .filter(|s| !s.is_empty())
        {
            return name;
        }
    }

    std::env::var("HOSTNAME")
        .or_else(|_| std::env::var("COMPUTERNAME"))
        .unwrap_or_else(|_| "unknown".to_string())
}

fn user_name() -> String {
    std::env::var("USER")
        .or_else(|_| std::env::var("USERNAME"))
        .unwrap_or_else(|_| "unknown".to_string())
}

/// .NET's Environment.UserDomainName returns the machine name on Unix, so fall
/// back to the hostname when no domain env var is present.
fn user_domain() -> String {
    std::env::var("USERDOMAIN")
        .or_else(|_| std::env::var("USERDNSDOMAIN"))
        .unwrap_or_else(|_| host_name())
}

/// Best-effort OS version string (mirrors .NET's Environment.OSVersion). On
/// Unix this shells out to `uname -r`, matching how `os_name` is detected.
fn os_version() -> String {
    #[cfg(unix)]
    {
        std::process::Command::new("uname")
            .arg("-r")
            .output()
            .ok()
            .and_then(|o| String::from_utf8(o.stdout).ok())
            .map(|s| s.trim().to_string())
            .filter(|s| !s.is_empty())
            .unwrap_or_else(|| "unknown".to_string())
    }
    #[cfg(not(unix))]
    {
        std::env::var("OS").unwrap_or_else(|_| "unknown".to_string())
    }
}

fn current_dir() -> String {
    std::env::current_dir()
        .map(|p| p.display().to_string())
        .unwrap_or_default()
}

fn os_name() -> &'static str {
    match std::env::consts::OS {
        "macos" => "macOS",
        "windows" => "Windows",
        "linux" => "Linux",
        other => other,
    }
}

fn arch() -> &'static str {
    std::env::consts::ARCH
}
