

using System;
using System.Collections.Generic;


namespace legr
{
    public class BaseTest
    {
        Microsoft.PowerShell.Commands.GroupInfo Microsoft.PowerShell.Commands.GroupInfo Microsoft.PowerShell.Commands.GroupInfo Microsoft.PowerShell.Commands.GroupInfo Microsoft.PowerShell.Commands.GroupInfo Microsoft.PowerShell.Commands.GroupInfo Microsoft.PowerShell.Commands.GroupInfo Microsoft.PowerShell.Commands.GroupInfo Microsoft.PowerShell.Commands.GroupInfo Microsoft.PowerShell.Commands.GroupInfo Microsoft.PowerShell.Commands.GroupInfo Microsoft.PowerShell.Commands.GroupInfo Microsoft.PowerShell.Commands.GroupInfo Microsoft.PowerShell.Commands.GroupInfo Microsoft.PowerShell.Commands.GroupInfo Microsoft.PowerShell.Commands.GroupInfo protected static Stack <Account>lastAccount = new Stack<Account>();
 protected static Dictionary< long, Account> mapAccount = new Dictionary<long, Account>();
 Microsoft.PowerShell.Commands.GroupInfo Microsoft.PowerShell.Commands.GroupInfo Microsoft.PowerShell.Commands.GroupInfo Microsoft.PowerShell.Commands.GroupInfo Microsoft.PowerShell.Commands.GroupInfo Microsoft.PowerShell.Commands.GroupInfo Microsoft.PowerShell.Commands.GroupInfo Microsoft.PowerShell.Commands.GroupInfo Microsoft.PowerShell.Commands.GroupInfo Microsoft.PowerShell.Commands.GroupInfo Microsoft.PowerShell.Commands.GroupInfo Microsoft.PowerShell.Commands.GroupInfo Microsoft.PowerShell.Commands.GroupInfo Microsoft.PowerShell.Commands.GroupInfo Microsoft.PowerShell.Commands.GroupInfo Microsoft.PowerShell.Commands.GroupInfo protected static Stack <Bill>lastBill = new Stack<Bill>();
 protected static Dictionary< long, Bill> mapBill = new Dictionary<long, Bill>();
 Microsoft.PowerShell.Commands.GroupInfo Microsoft.PowerShell.Commands.GroupInfo Microsoft.PowerShell.Commands.GroupInfo Microsoft.PowerShell.Commands.GroupInfo Microsoft.PowerShell.Commands.GroupInfo Microsoft.PowerShell.Commands.GroupInfo Microsoft.PowerShell.Commands.GroupInfo Microsoft.PowerShell.Commands.GroupInfo Microsoft.PowerShell.Commands.GroupInfo Microsoft.PowerShell.Commands.GroupInfo Microsoft.PowerShell.Commands.GroupInfo Microsoft.PowerShell.Commands.GroupInfo Microsoft.PowerShell.Commands.GroupInfo Microsoft.PowerShell.Commands.GroupInfo Microsoft.PowerShell.Commands.GroupInfo Microsoft.PowerShell.Commands.GroupInfo protected static Stack <BillItem>lastBillItem = new Stack<BillItem>();
 protected static Dictionary< long, BillItem> mapBillItem = new Dictionary<long, BillItem>();
 Microsoft.PowerShell.Commands.GroupInfo Microsoft.PowerShell.Commands.GroupInfo Microsoft.PowerShell.Commands.GroupInfo Microsoft.PowerShell.Commands.GroupInfo Microsoft.PowerShell.Commands.GroupInfo Microsoft.PowerShell.Commands.GroupInfo Microsoft.PowerShell.Commands.GroupInfo Microsoft.PowerShell.Commands.GroupInfo Microsoft.PowerShell.Commands.GroupInfo Microsoft.PowerShell.Commands.GroupInfo Microsoft.PowerShell.Commands.GroupInfo Microsoft.PowerShell.Commands.GroupInfo Microsoft.PowerShell.Commands.GroupInfo Microsoft.PowerShell.Commands.GroupInfo Microsoft.PowerShell.Commands.GroupInfo Microsoft.PowerShell.Commands.GroupInfo protected static Stack <Budget>lastBudget = new Stack<Budget>();
 protected static Dictionary< long, Budget> mapBudget = new Dictionary<long, Budget>();
 Microsoft.PowerShell.Commands.GroupInfo Microsoft.PowerShell.Commands.GroupInfo Microsoft.PowerShell.Commands.GroupInfo Microsoft.PowerShell.Commands.GroupInfo Microsoft.PowerShell.Commands.GroupInfo Microsoft.PowerShell.Commands.GroupInfo Microsoft.PowerShell.Commands.GroupInfo Microsoft.PowerShell.Commands.GroupInfo Microsoft.PowerShell.Commands.GroupInfo Microsoft.PowerShell.Commands.GroupInfo Microsoft.PowerShell.Commands.GroupInfo Microsoft.PowerShell.Commands.GroupInfo Microsoft.PowerShell.Commands.GroupInfo Microsoft.PowerShell.Commands.GroupInfo Microsoft.PowerShell.Commands.GroupInfo Microsoft.PowerShell.Commands.GroupInfo protected static Stack <Category>lastCategory = new Stack<Category>();
 protected static Dictionary< long, Category> mapCategory = new Dictionary<long, Category>();
 Microsoft.PowerShell.Commands.GroupInfo Microsoft.PowerShell.Commands.GroupInfo Microsoft.PowerShell.Commands.GroupInfo Microsoft.PowerShell.Commands.GroupInfo Microsoft.PowerShell.Commands.GroupInfo Microsoft.PowerShell.Commands.GroupInfo Microsoft.PowerShell.Commands.GroupInfo Microsoft.PowerShell.Commands.GroupInfo Microsoft.PowerShell.Commands.GroupInfo Microsoft.PowerShell.Commands.GroupInfo Microsoft.PowerShell.Commands.GroupInfo Microsoft.PowerShell.Commands.GroupInfo Microsoft.PowerShell.Commands.GroupInfo Microsoft.PowerShell.Commands.GroupInfo Microsoft.PowerShell.Commands.GroupInfo Microsoft.PowerShell.Commands.GroupInfo protected static Stack <Customer>lastCustomer = new Stack<Customer>();
 protected static Dictionary< long, Customer> mapCustomer = new Dictionary<long, Customer>();
 Microsoft.PowerShell.Commands.GroupInfo Microsoft.PowerShell.Commands.GroupInfo Microsoft.PowerShell.Commands.GroupInfo Microsoft.PowerShell.Commands.GroupInfo Microsoft.PowerShell.Commands.GroupInfo Microsoft.PowerShell.Commands.GroupInfo Microsoft.PowerShell.Commands.GroupInfo Microsoft.PowerShell.Commands.GroupInfo Microsoft.PowerShell.Commands.GroupInfo Microsoft.PowerShell.Commands.GroupInfo Microsoft.PowerShell.Commands.GroupInfo Microsoft.PowerShell.Commands.GroupInfo Microsoft.PowerShell.Commands.GroupInfo Microsoft.PowerShell.Commands.GroupInfo Microsoft.PowerShell.Commands.GroupInfo Microsoft.PowerShell.Commands.GroupInfo protected static Stack <Invoice>lastInvoice = new Stack<Invoice>();
 protected static Dictionary< long, Invoice> mapInvoice = new Dictionary<long, Invoice>();
 Microsoft.PowerShell.Commands.GroupInfo Microsoft.PowerShell.Commands.GroupInfo Microsoft.PowerShell.Commands.GroupInfo Microsoft.PowerShell.Commands.GroupInfo Microsoft.PowerShell.Commands.GroupInfo Microsoft.PowerShell.Commands.GroupInfo Microsoft.PowerShell.Commands.GroupInfo Microsoft.PowerShell.Commands.GroupInfo Microsoft.PowerShell.Commands.GroupInfo Microsoft.PowerShell.Commands.GroupInfo Microsoft.PowerShell.Commands.GroupInfo Microsoft.PowerShell.Commands.GroupInfo Microsoft.PowerShell.Commands.GroupInfo Microsoft.PowerShell.Commands.GroupInfo Microsoft.PowerShell.Commands.GroupInfo Microsoft.PowerShell.Commands.GroupInfo protected static Stack <InvoiceItem>lastInvoiceItem = new Stack<InvoiceItem>();
 protected static Dictionary< long, InvoiceItem> mapInvoiceItem = new Dictionary<long, InvoiceItem>();
 Microsoft.PowerShell.Commands.GroupInfo Microsoft.PowerShell.Commands.GroupInfo Microsoft.PowerShell.Commands.GroupInfo Microsoft.PowerShell.Commands.GroupInfo Microsoft.PowerShell.Commands.GroupInfo Microsoft.PowerShell.Commands.GroupInfo Microsoft.PowerShell.Commands.GroupInfo Microsoft.PowerShell.Commands.GroupInfo Microsoft.PowerShell.Commands.GroupInfo Microsoft.PowerShell.Commands.GroupInfo Microsoft.PowerShell.Commands.GroupInfo Microsoft.PowerShell.Commands.GroupInfo Microsoft.PowerShell.Commands.GroupInfo Microsoft.PowerShell.Commands.GroupInfo Microsoft.PowerShell.Commands.GroupInfo Microsoft.PowerShell.Commands.GroupInfo protected static Stack <Org>lastOrg = new Stack<Org>();
 protected static Dictionary< long, Org> mapOrg = new Dictionary<long, Org>();
 Microsoft.PowerShell.Commands.GroupInfo Microsoft.PowerShell.Commands.GroupInfo Microsoft.PowerShell.Commands.GroupInfo Microsoft.PowerShell.Commands.GroupInfo Microsoft.PowerShell.Commands.GroupInfo Microsoft.PowerShell.Commands.GroupInfo Microsoft.PowerShell.Commands.GroupInfo Microsoft.PowerShell.Commands.GroupInfo Microsoft.PowerShell.Commands.GroupInfo Microsoft.PowerShell.Commands.GroupInfo Microsoft.PowerShell.Commands.GroupInfo Microsoft.PowerShell.Commands.GroupInfo Microsoft.PowerShell.Commands.GroupInfo Microsoft.PowerShell.Commands.GroupInfo Microsoft.PowerShell.Commands.GroupInfo Microsoft.PowerShell.Commands.GroupInfo protected static Stack <Payment>lastPayment = new Stack<Payment>();
 protected static Dictionary< long, Payment> mapPayment = new Dictionary<long, Payment>();
 Microsoft.PowerShell.Commands.GroupInfo Microsoft.PowerShell.Commands.GroupInfo Microsoft.PowerShell.Commands.GroupInfo Microsoft.PowerShell.Commands.GroupInfo Microsoft.PowerShell.Commands.GroupInfo Microsoft.PowerShell.Commands.GroupInfo Microsoft.PowerShell.Commands.GroupInfo Microsoft.PowerShell.Commands.GroupInfo Microsoft.PowerShell.Commands.GroupInfo Microsoft.PowerShell.Commands.GroupInfo Microsoft.PowerShell.Commands.GroupInfo Microsoft.PowerShell.Commands.GroupInfo Microsoft.PowerShell.Commands.GroupInfo Microsoft.PowerShell.Commands.GroupInfo Microsoft.PowerShell.Commands.GroupInfo Microsoft.PowerShell.Commands.GroupInfo protected static Stack <Transaction>lastTransaction = new Stack<Transaction>();
 protected static Dictionary< long, Transaction> mapTransaction = new Dictionary<long, Transaction>();
 Microsoft.PowerShell.Commands.GroupInfo Microsoft.PowerShell.Commands.GroupInfo Microsoft.PowerShell.Commands.GroupInfo Microsoft.PowerShell.Commands.GroupInfo Microsoft.PowerShell.Commands.GroupInfo Microsoft.PowerShell.Commands.GroupInfo Microsoft.PowerShell.Commands.GroupInfo Microsoft.PowerShell.Commands.GroupInfo Microsoft.PowerShell.Commands.GroupInfo Microsoft.PowerShell.Commands.GroupInfo Microsoft.PowerShell.Commands.GroupInfo Microsoft.PowerShell.Commands.GroupInfo Microsoft.PowerShell.Commands.GroupInfo Microsoft.PowerShell.Commands.GroupInfo Microsoft.PowerShell.Commands.GroupInfo Microsoft.PowerShell.Commands.GroupInfo protected static Stack <TransactionCategory>lastTransactionCategory = new Stack<TransactionCategory>();
 protected static Dictionary< long, TransactionCategory> mapTransactionCategory = new Dictionary<long, TransactionCategory>();
 Microsoft.PowerShell.Commands.GroupInfo Microsoft.PowerShell.Commands.GroupInfo Microsoft.PowerShell.Commands.GroupInfo Microsoft.PowerShell.Commands.GroupInfo Microsoft.PowerShell.Commands.GroupInfo Microsoft.PowerShell.Commands.GroupInfo Microsoft.PowerShell.Commands.GroupInfo Microsoft.PowerShell.Commands.GroupInfo Microsoft.PowerShell.Commands.GroupInfo Microsoft.PowerShell.Commands.GroupInfo Microsoft.PowerShell.Commands.GroupInfo Microsoft.PowerShell.Commands.GroupInfo Microsoft.PowerShell.Commands.GroupInfo Microsoft.PowerShell.Commands.GroupInfo Microsoft.PowerShell.Commands.GroupInfo Microsoft.PowerShell.Commands.GroupInfo protected static Stack <User>lastUser = new Stack<User>();
 protected static Dictionary< long, User> mapUser = new Dictionary<long, User>();
 Microsoft.PowerShell.Commands.GroupInfo Microsoft.PowerShell.Commands.GroupInfo Microsoft.PowerShell.Commands.GroupInfo Microsoft.PowerShell.Commands.GroupInfo Microsoft.PowerShell.Commands.GroupInfo Microsoft.PowerShell.Commands.GroupInfo Microsoft.PowerShell.Commands.GroupInfo Microsoft.PowerShell.Commands.GroupInfo Microsoft.PowerShell.Commands.GroupInfo Microsoft.PowerShell.Commands.GroupInfo Microsoft.PowerShell.Commands.GroupInfo Microsoft.PowerShell.Commands.GroupInfo Microsoft.PowerShell.Commands.GroupInfo Microsoft.PowerShell.Commands.GroupInfo Microsoft.PowerShell.Commands.GroupInfo Microsoft.PowerShell.Commands.GroupInfo protected static Stack <UserOrg>lastUserOrg = new Stack<UserOrg>();
 protected static Dictionary< long, UserOrg> mapUserOrg = new Dictionary<long, UserOrg>();
 Microsoft.PowerShell.Commands.GroupInfo Microsoft.PowerShell.Commands.GroupInfo Microsoft.PowerShell.Commands.GroupInfo Microsoft.PowerShell.Commands.GroupInfo Microsoft.PowerShell.Commands.GroupInfo Microsoft.PowerShell.Commands.GroupInfo Microsoft.PowerShell.Commands.GroupInfo Microsoft.PowerShell.Commands.GroupInfo Microsoft.PowerShell.Commands.GroupInfo Microsoft.PowerShell.Commands.GroupInfo Microsoft.PowerShell.Commands.GroupInfo Microsoft.PowerShell.Commands.GroupInfo Microsoft.PowerShell.Commands.GroupInfo Microsoft.PowerShell.Commands.GroupInfo Microsoft.PowerShell.Commands.GroupInfo Microsoft.PowerShell.Commands.GroupInfo protected static Stack <Vendor>lastVendor = new Stack<Vendor>();
 protected static Dictionary< long, Vendor> mapVendor = new Dictionary<long, Vendor>();

        
    }
}



