// <auto-generated>
// Rust port of ScriptProviderFactory.core.cs.
//
// Selects a ScriptProvider for a script type. The .NET factory mapped
// script_type_id to C#/PowerShell/Python compilers; the Rust runtime uses Rhai
// as the engine. Additional language providers can be selected here later.
// </auto-generated>

use crate::i_script_provider::ScriptProvider;
use crate::rhai_provider::RhaiProvider;

pub struct ScriptProviderFactory;

impl ScriptProviderFactory {
    pub fn create_provider(_script_type_id: i64) -> Box<dyn ScriptProvider> {
        Box::new(RhaiProvider::new())
    }
}
