// <auto-generated>
// Rust port of the ScriptHost portion of ScriptHost.core.cs.
//
// Runs a script row (a core.script record carrying `source`, `name`,
// `script_type_id`) against a ScriptContext: picks a provider, executes, and
// surfaces failures (errors percolate to the caller; ret_code != 0 is an error).
// </auto-generated>

use common::{BaseObject, Logger};
use serde_json::Value;

use crate::i_script_provider::ScriptError;
use crate::script_context::ScriptContext;
use crate::script_provider_factory::ScriptProviderFactory;

pub struct ScriptHost;

impl ScriptHost {
    /// Execute the script described by `script_obj` against `ctx`.
    pub fn invoke(ctx: &mut ScriptContext, script_obj: &BaseObject) -> Result<(), ScriptError> {
        let source = match script_obj.get("source") {
            Value::String(s) => s,
            // No source -> nothing to do (parity with the .NET guard).
            _ => return Ok(()),
        };
        let name = match script_obj.get("name") {
            Value::String(s) => s,
            _ => "(unnamed)".to_string(),
        };
        let script_type_id = script_obj.get("script_type_id").as_i64().unwrap_or(0);

        ctx.ret_code = 0;
        ctx.script_exception = None;
        ctx.script_result = None;

        Logger::debug(format!("Executing script '{}' (type {})", name, script_type_id));

        let provider = ScriptProviderFactory::create_provider(script_type_id);
        match provider.compile_and_execute(&source, ctx) {
            Ok(()) => {
                if ctx.ret_code != 0 {
                    Logger::error(format!(
                        "script '{}' signalled return code {}",
                        name, ctx.ret_code
                    ));
                    return Err(ScriptError::ReturnCode { name, code: ctx.ret_code });
                }
                Ok(())
            }
            Err(e) => {
                ctx.script_exception = Some(e.to_string());
                Logger::error(format!("Exception in script '{}': {}", name, e));
                Err(e)
            }
        }
    }
}
