TARGETDIR=./bin/Debug/net9.0

default: build

build:
	@@dotnet restore
	@@dotnet build
	@@cp -r -f ./appsettings.json $(TARGETDIR)

clean:
	@@rm -rf ./bin
	@@rm -rf ./obj

restore:
	@@dotnet restore

run:
	@@dotnet run

publish:
	@@dotnet publish -c Release
