TARGETDIR=../../bin/web

default: build

build:
	@@dotnet restore
	@@dotnet build
	@@mkdir -p $(TARGETDIR)/wwwroot
	@@cp -r -f . $(TARGETDIR)
	@@cp -f ../../usr/web/wwwroot/appsettings.json $(TARGETDIR)/wwwroot


clean:
	@@rm -rf ./bin
	@@rm -rf ./obj

restore:
	@@dotnet restore

run:
	@@dotnet run

publish:
	@@dotnet publish -c Release
