// <auto-generated>
// Rust port of test-script Program.cs. The .NET harness exercised the
// ScriptHost with C#, PowerShell and Python scripts; the Rust runtime uses one
// engine — Rhai — so this drives a single set of Rhai examples that cover the
// same ground (simple expression, loop, context/args access, exception, return
// code) plus the host capabilities registered on the engine (logging, and
// Logic-routed database access).
// </auto-generated>
#![allow(clippy::all)]

use common::BaseObject;
use script::{ScriptContext, ScriptHost};
use serde_json::json;

/// Build a one-off `core.script`-shaped record and run it via the ScriptHost.
fn run(name: &str, source: &str, ctx: &mut ScriptContext) {
    println!("Test: {name}");

    let mut script_row = BaseObject::new();
    script_row.set("name", json!(name));
    script_row.set("source", json!(source));
    script_row.set("script_type_id", json!(0)); // Rhai (the factory ignores the id)

    match ScriptHost::invoke(ctx, &script_row) {
        Ok(()) => match &ctx.script_result {
            Some(result) => println!("  ok - result: {result}"),
            None => println!("  ok"),
        },
        Err(e) => println!("  error (ret_code={}): {e}", ctx.ret_code),
    }
    println!();
}

fn main() {
    println!("=== Testing Rhai scripting via ScriptHost ===\n");

    let mut ctx = ScriptContext::new();

    run(
        "Simple expression",
        r#"log_info("Hello from a Rhai script!"); 40 + 2"#,
        &mut ctx,
    );

    run(
        "Loop",
        r#"
            log_info("Executing loop script");
            for i in 0..3 {
                log_info(`  iteration ${i}`);
            }
        "#,
        &mut ctx,
    );

    // Seed the triggering record and the inputs, then let the script read and
    // mutate them; mutations to `ctx` are written back after execution.
    ctx.transaction.set("msg", json!("initial value"));
    ctx.args.insert("testKey".to_string(), json!("testValue"));
    run(
        "Context + args access",
        r#"
            log_info(`ctx.msg       = ${ctx.msg}`);
            log_info(`args.testKey  = ${args.testKey}`);
            ctx.msg = "updated by script";
            ctx.msg
        "#,
        &mut ctx,
    );
    println!("  (record `msg` is now: {:?})\n", ctx.transaction.get("msg"));

    // Expected-to-fail cases: the error percolates and is reported per example.
    run(
        "Exception handling",
        r#"log_info("about to throw"); throw "boom from a Rhai script""#,
        &mut ctx,
    );

    run(
        "Return code",
        r#"log_info("setting ret_code = 2"); let ret_code = 2;"#,
        &mut ctx,
    );

    // Capabilities that need a live database / network. These surface a real
    // error (and the harness keeps going) if the resource isn't available.
    println!("--- DB / HTTP capabilities (require a live database / network) ---\n");
    run(
        "DB select through Logic",
        r#"let rows = db_select("op_role"); log_info(`op_role rows: ${rows.len()}`)"#,
        &mut ctx,
    );

    println!("=== Done ===");
}
