TARGETDIR=../../../bin/scheduler/net9.0

default: build

build:
	@@dotnet build
	@@mkdir -p $(TARGETDIR)
	@@cp -r -f ../../../usr/server/scheduler/appsettings.json $(TARGETDIR)

clean:
	@@rm -rf ./bin
